services:
  user_app:
    image: 'user_app:latest'
    container_name: 'user_app'
    depends_on:
      - 'user_db'
    ports:
      - '8080:8080'
    environment:
      spring_datasource_url: 'jdbc:postgresql://user_db:5432/user_db'
      spring_datasource_username: 'root'
      spring_datasource_password: 'secret'
      spring_datasource_driver-class-name: 'org.postgresql.Driver'
      spring_jpa_properties_hibernate_dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      spring_jpa_hibernate_ddl-auto: 'create-drop'
      spring_jpa_defer-datasource-initialization: 'true'
      spring_sql_init_mode: 'always'
      spring_integration_jdbc_initialize-schema: 'always'
  user_db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'user_db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - '5431:5432'
  product_app:
    image: 'product_app:latest'
    container_name: 'product_app'
    depends_on:
      - 'product_db'
    ports:
      - '8081:8081'
    environment:
      spring_datasource_url: 'jdbc:postgresql://product_db:5432/product_db'
      spring_datasource_username: 'root'
      spring_datasource_password: 'secret'
      spring_datasource_driver-class-name: 'org.postgresql.Driver'
      spring_jpa_properties_hibernate_dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      spring_jpa_hibernate_ddl-auto: 'create-drop'
      spring_jpa_defer-datasource-initialization: 'true'
      spring_sql_init_mode: 'always'
      spring_integration_jdbc_initialize-schema: 'always'
  product_db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'product_db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - '5432:5432'